#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : envs
Version  : 1.2.6
Release  : 2
URL      : https://files.pythonhosted.org/packages/34/f5/5277e967127581e5a63dca21dd42b43ab5d21ddd03cad0459649ee3c210a/envs-1.2.6.tar.gz
Source0  : https://files.pythonhosted.org/packages/34/f5/5277e967127581e5a63dca21dd42b43ab5d21ddd03cad0459649ee3c210a/envs-1.2.6.tar.gz
Summary  : Easy access of environment variables from Python with support for strings, booleans, list, tuples, and dicts.
Group    : Development/Tools
License  : Apache-2.0 GPL-3.0
Requires: envs-bin
Requires: envs-python3
Requires: envs-license
Requires: envs-python
Requires: Jinja2
Requires: click
BuildRequires : buildreq-distutils3

%description
# envs
Easy access of environment variables from Python with support for booleans, strings, lists, tuples, integers, floats, and dicts.

%package bin
Summary: bin components for the envs package.
Group: Binaries
Requires: envs-license

%description bin
bin components for the envs package.


%package license
Summary: license components for the envs package.
Group: Default

%description license
license components for the envs package.


%package python
Summary: python components for the envs package.
Group: Default
Requires: envs-python3

%description python
python components for the envs package.


%package python3
Summary: python3 components for the envs package.
Group: Default
Requires: python3-core

%description python3
python3 components for the envs package.


%prep
%setup -q -n envs-1.2.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534860497
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/envs
cp LICENSE %{buildroot}/usr/share/doc/envs/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/envs

%files license
%defattr(-,root,root,-)
/usr/share/doc/envs/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
